# -*- coding: utf-8 -*-
"""MyGoogleAssistantProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12x5axwuAGfRh2HIKccJIzVdhtDVKOfHJ

Give input text, some question
Based on the question, decide what to do? On device operation Who are you kind of messages? Asking the assistant some question?
Give proper answer for each one of these responses
If the question is related to search internet, get the answer from Google Gemeni model
If you got an answer, then please convert it to Text to Speech using GTTS.
"""

!pip install -q -U google-generativeai

!pip install gTTS

import pathlib
import textwrap
from gtts import gTTS

import google.generativeai as genai

from IPython.display import display
from IPython.display import Markdown
from IPython.display import Audio, display


def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

genai.configure(api_key=GoogleApiKey)

from google.colab import userdata
GoogleApiKey=userdata.get('GoogleApiKey')
model = genai.GenerativeModel('gemini-pro')

#step 1
def ask_question(name):
  ques='Hey '+ name + ' what do you want ?'
  ques = input(ques)
  return ques

ask_question()

def classify_questions(ques):
  goahead_with_web_search=False
  device_lst=['Set an alarm','Set a reminder','Send a message','Call']
  personal_lst=['who are you?','Who created you?']

  device=False
  for i in device_lst:
    if i in ques:
      device=True

  if device:
    print("This question is related to Device things, which is not supported in out Google Assistant!")

  personal_question=False
  for i in personal_lst:
    if i in ques.lower():
      personal_question=True

  if personal_question:
      print("Hey, I am your personal assistant created by Aditya")


  if device:
    goahead_with_web_search=False
  elif personal_question:
    goahead_with_web_search=False
  else:
    goahead_with_web_search=True

  return goahead_with_web_search

classify_questions("Who are you?")

#start searching with google gemeni

def ask_gemini(ques):
  modified_prompt='Hey give me answer to this question ' + ques + ' in maximum of 40 words'
  response=model.generate_content(modified_prompt)
  to_markdown(response.text)
  return response.text

def speak(answer):
  tts=gTTS(answer)
  tts.save('audio.mp3')
  display(Audio('audio.mp3', autoplay=True))

have_any_other_ques='y'
name=''
while have_any_other_ques=='y':
  if name=='':
    name=input("Hey, what is your name?-")

  q=ask_question(name)

  go_ahead=classify_questions(q)
  answer=''

  if go_ahead==True:
    answer=ask_gemini(q)
    speak(answer)
    print(answer)

  have_any_other_ques=input("Do you have any other questions??")